import type { NextPage } from "next";
import Head from "next/head";
import Home from "../src/component/home";

const Index: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>MooNs Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
};

export default Index;
